# FROM: Indicates the base image and version to build on top of
FROM nginx:latest

# COPY: Copies files from local machine into image (local path, destination path in image)
COPY ./proxy.conf /etc/nginx/conf.d/default.conf
